name: "Run Tests"
invalid-key: test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Echo variable
        shell: bash
        run: echo hello world
